<?php
/**
 * @file
 * Code for the Stanford Conference feature.
 */

include_once 'stanford_conference.features.inc';

/**
 * Implements hook_theme().
 */
function stanford_conference_theme($existing, $type, $theme, $path) {
  return array(
    'views_view_unformatted__conference_session_agenda' => array(
      'variables' => array('view' => NULL, 'options' => NULL, 'row' => NULL),
      'template' => 'views-view-unformatted--conference-session-agenda',
      'base hook' => 'views_view_unformatted',
      'path' => drupal_get_path('module', 'stanford_conference') . '/views',
    ),
  );
}
