<?php
/**
 * @file
 * File description
 *
 * Long description
 */

/**
 * Implements hook_system_info_alter().
 * @param $info The .info file contents, passed by reference so that it can be altered.
 * @param $file Full information about the module or theme, including $file->name, and $file->filename.
 * @param $type Either 'module' or 'theme', depending on the type of .info file that was passed.
 */
function acsf_helper_system_info_alter(&$info, $file, $type) {
  // Remove the dependency on the ACSF_OPENID module.
  if (isset($info['project']) && $info['project'] == "acsf") {
    $search = array_search("acsf_openid", $info['dependencies']);
    if ($search !== FALSE && $info['dependencies'][$search] == "acsf_openid") {
      unset($info['dependencies'][$search]);
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * @param $form Nested array of form elements that comprise the form.
 * @param $form_state A keyed array containing the current state of the form. The arguments that drupal_get_form() was originally called with are available in the array $form_state['build_info']['args'].
 * @param $form_id String representing the name of the form itself. Typically this is the name of the function that generated the form.
 */
function acsf_helper_form_system_modules_alter(&$form, &$form_state, $form_id) {
  unset($form['modules']['Core']['statistics']);
  unset($form['modules']['Other']['mollom']);
  unset($form['modules']['Services - servers']['xmlrpc_server']);
  unset($form['modules']['Stanford']['capx_webauth']);
  unset($form['modules']['Stanford']['stanford_metatag_nobots']);
  unset($form['modules']['Stanford']['stanford_webauth_block']);
  unset($form['modules']['Stanford']['webauth']);
  unset($form['modules']['Stanford']['webauth_extras']);
  unset($form['modules']['Stanford - ACSF']['acsf_helper']);
}

/**
 * Implements hook_module_implements_alter().
 */
function acsf_helper_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'form_alter' && module_exists('paranoia')) {
    $group = $implementations['paranoia'];
    unset($implementations['paranoia']);
    $implementations['paranoia'] = $group;
  }
}

/**
 * Implements hook_page_build().
 *
 * Handles 404 redirect for the sites.stanford.edu site.
 *
 * We do this here rather than in hook_init() because we want redirect and
 * match_redirect to have a chance to act first.
 *
 * @param array &$page
 *   The page render array.
 */
function acsf_helper_page_build(array &$page) {
  // When a site is not found and a redirect is not found on
  // sites.stanford.edu/something-something we want to redirect to UIT page.
  global $conf;
  $headers = drupal_get_http_header();
  $is_ah = $_ENV['AH_SITE_GROUP'] ?? FALSE;
  // 7481 resolves to the site at sites.stanford.edu.
  $key_site_id = variable_get("acsf_helper_key_site_id", "7481");

  // If Drupal hits a 404, we should check to see if we are on a valid site.
  // When we are not, there is no site_id.
  // Perform this check only on the AH environment.
  if ($is_ah && isset($headers["status"]) && $headers["status"] == "404 Not Found") {
    if ($key_site_id == (string) $conf['gardens_site_id']) {
      header("Location:https://uit.stanford.edu/service/stanfordsites");
      drupal_exit();
    }
  }

}

